#ifndef TOKENS_H
#define TOKENS_H
#include <stdint.h>
#include <stdlib.h>
#define MAX_TOKEN_LENGTH 12 //Allows storing largest 32 bit number (includes null terminator)



typedef enum TOKEN_ID {

    TOKEN_INVALID = -1,    
    TOKEN_IDENTIFIER = -2,
    TOKEN_LITERAL = -3,

    TOKEN_KEYWORD_DEF,
    TOKEN_KEYWORD_RETURN,
    TOKEN_KEYWORD_LET,
    TOKEN_KEYWORD_INT,
    TOKEN_KEYWORD_IF,
    TOKEN_KEYWORD_ELIF,
    TOKEN_KEYWORD_ELSE,
    TOKEN_KEYWORD_WHILE,

    TOKEN_SYMBOL_PLUS,
    TOKEN_SYMBOL_MINUS,
    TOKEN_SYMBOL_ASTERISK,
    TOKEN_SYMBOL_SLASH,
    TOKEN_SYMBOL_EQUAL,
    TOKEN_SYMBOL_DOUBLE_EQUAL,
    TOKEN_SYMBOL_NOT_EQUAL,
    TOKEN_SYMBOL_LESS_THAN,
    TOKEN_SYMBOL_GREATER_THAN,
    TOKEN_SYMBOL_LESS_EQUAL,
    TOKEN_SYMBOL_GREATER_EQUAL,
    TOKEN_SYMBOL_LEFT_PAREN,
    TOKEN_SYMBOL_RIGHT_PAREN,
    TOKEN_SYMBOL_LEFT_CURLY_BRACE,
    TOKEN_SYMBOL_RIGHT_CURLY_BRACE,
    TOKEN_SYMBOL_SEMICOLON,

} TOKEN_ID;

extern const char *TOKEN_VECTOR[];
extern const size_t TOKEN_VECTOR_SIZE;


#endif //TOKENS_H
